import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

/**
 * Pretendard — Body / Caption 및 기본 본문 폰트
 *
 * 디자인 시스템에서 사용하는 weight만 로드:
 *   Regular (400) · Medium (500) · Bold (700)
 * Black/SemiBold/Light 등 그 외 weight는 시스템 외 사용으로 간주하여 비포함.
 *
 * 노출 CSS 변수: --font-pretendard
 * globals.css 의 --font-family-pretendard 가 이 변수를 참조한다.
 */
const pretendard = localFont({
  variable: "--font-pretendard",
  display: "swap",
  src: [
    {
      path: "../public/fonts/Pretendard-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Pretendard-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Pretendard-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

/**
 * SUITE — Display / Heading 폰트
 *
 * variable font 단일 파일로 디자인 시스템이 공식 사용하는 가중치를 커버:
 *   Regular (400) · Bold (700) · ExtraBold (800)
 * weight 범위는 variable font 의 전체 지원 범위(400–800)를 그대로 유지하여
 * 미래에 디자인 시스템이 다른 가중치를 추가해도 폰트 로딩은 변경 없이 대응한다.
 *
 * 노출 CSS 변수: --font-suite
 * globals.css 의 --font-family-suite 가 이 변수를 참조한다.
 */
const suite = localFont({
  variable: "--font-suite",
  display: "swap",
  src: "../public/fonts/SUITE-Variable.woff2",
  weight: "400 800",
});

/**
 * Daiso — 프로모션 / Display typography 폰트 (한글 glyph 포함)
 *
 * Typography 3-family system 에서의 역할:
 *   - Pretendard : 기본 UI typography
 *   - SUITE      : 브랜드성 Heading / 강조 (일반 UI Heading 기본값)
 *   - Daiso      : 프로모션 / Display typography  ← 본 폰트
 *
 * 사용 규칙 (디자인 시스템 정의):
 *   - 일반 body typography 사용 금지.
 *   - 일반 UI Heading 의 기본값으로 사용 금지 (기본은 SUITE).
 *   - 프로모션 타이틀, 메인 비주얼 카피, 디스플레이 영역에서 사용.
 *   - Pretendard 컨텍스트에 함께 쓸 때는 동일 font-size 유지 (family 만 swap).
 *   - 단일 weight 폰트 → font-weight 토큰 적용 불필요.
 *
 * 노출 CSS 변수: --font-daiso
 * globals.css 의 --font-family-daiso 가 이 변수를 참조하며,
 * 두 가지 그룹의 페어드 토큰으로 사용 규칙을 인코딩:
 *   1. --text-{body|caption}-{n}-daiso  — Pretendard 컨텍스트 family swap (size 동일)
 *   2. --text-daiso-display-{1,2}       — 프로모션 / Display 전용 별도 tier
 *
 * 가격 강조(+2pt) 는 commerce pricing emphasis rule 로 별도 관리.
 * typography foundation 에서는 정의하지 않음.
 */
const daiso = localFont({
  variable: "--font-daiso",
  display: "swap",
  src: "../public/fonts/Daiso.otf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} ${suite.variable} ${daiso.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
